export const metadata = {
   title: "Login",
   description: "Generated by Next.js",
};

import "../(home)/global.css";

export default function RootLayout({ children }) {
   return (
      <html lang='pt-br'>
         <body>{children}</body>
      </html>
   );
}
