import {
   MdAirplaneTicket,
   MdAirplanemodeInactive,
   MdHail,
   MdOutlinePeopleAlt,
   MdHome,
   MdMoney,
   MdAccountBalance,
   MdAssignment,
   MdAttachMoney,
   MdCalendarViewWeek,
   MdFlightTakeoff,
   MdBarChart,
   MdHealthAndSafety,
   MdMedicalServices,
   MdStorage,
   MdSecurity,
   MdGroups,
   MdSchool,
   MdTranslate,
   MdPolicy,
   MdBadge,
   MdSort,
   MdEventAvailable,
} from "react-icons/md";
import { FaUsers, FaBuilding, FaSitemap } from "react-icons/fa6";
import { FaPaperPlane } from "react-icons/fa";
import { RiAdminLine } from "react-icons/ri";
import { GiSecurityGate, GiJoystick } from "react-icons/gi";
import { TbLogs } from "react-icons/tb";
import { ImStatsDots } from "react-icons/im";
import { CiPaperplane } from "react-icons/ci";

export const navItems = [
   {
      type: "item",
      icon: MdHome,
      label: "Início",
      path: "/",
      scope: "shared",
      roles: [],
   },
   {
      type: "collapse",
      icon: FaPaperPlane,
      label: "Operações",
      scope: "tenant",
      roles: [
         "ops_avancado",
         "ops_basico",
         "dout_avancado",
         "dout_basico",
         "apoio_avancado",
      ],
      children: [
         {
            icon: MdCalendarViewWeek,
            label: "Quadro Operacional",
            path: "/ops/quadro",
            resource: "quadro-oper",
            permission: "view",
         },
         {
            icon: MdAirplaneTicket,
            label: "Quadrinhos",
            path: "/ops/quads",
            resource: "quad_ops",
            permission: "view",
         },
         {
            icon: MdAssignment,
            label: "Ordens de Missão",
            path: "/ops/om",
            resource: "ordem_missao",
            permission: "view",
         },
         {
            icon: MdAirplanemodeInactive,
            label: "Indisponibilidades",
            path: "/ops/indisp",
            resource: "indisp_trips",
            permission: "view",
         },
         {
            icon: MdEventAvailable,
            label: "Escala",
            path: "/ops/escala",
            resource: "quad_ops",
            permission: "view",
         },
         {
            icon: MdHail,
            label: "Tripulantes",
            path: "/ops/trip",
            resource: "trips",
            permission: "view",
         },
         {
            icon: MdFlightTakeoff,
            label: "Aeronaves",
            path: "/ops/aeronaves",
            resource: "aeronaves",
            permission: "view",
         },
      ],
   },
   {
      type: "collapse",
      icon: MdBarChart,
      label: "Estatística",
      scope: "tenant",
      roles: [],
      children: [
         {
            icon: MdSort,
            label: "Pau de Sebo",
            path: "/estatistica/sebo",
            resource: "sebo",
            permission: "view",
         },
         {
            icon: CiPaperplane,
            label: "Etapas",
            path: "/estatistica/etapas",
            resource: "etapas",
            permission: "view",
         },
         {
            icon: ImStatsDots,
            label: "Esforço Aéreo",
            path: "/estatistica/esfaer",
            resource: "esf_aer",
            permission: "view",
         },
         {
            icon: MdFlightTakeoff,
            label: "Horas por ANV",
            path: "/estatistica/horas-anv",
            resource: "aeronaves",
            permission: "view",
         },
      ],
   },
   {
      type: "collapse",
      icon: MdHealthAndSafety,
      label: "Aeromédica",
      scope: "tenant",
      roles: [],
      children: [
         {
            icon: MdMedicalServices,
            label: "Cartões de Saúde",
            path: "/aeromedica/cartoes-saude",
            resource: "cartoes-saude",
            permission: "view",
         },
      ],
   },
   {
      type: "collapse",
      icon: MdSecurity,
      label: "Segurança de Voo",
      scope: "tenant",
      roles: [],
      children: [
         {
            icon: MdGroups,
            label: "CRM",
            path: "/seg-voo/crm",
            resource: "crm",
            permission: "view",
         },
      ],
   },
   {
      type: "collapse",
      icon: MdSchool,
      label: "Instrução",
      scope: "tenant",
      roles: [],
      children: [
         {
            icon: MdTranslate,
            label: "Idiomas",
            path: "/instrucao/idiomas",
            resource: "idiomas",
            permission: "view",
         },
         {
            icon: GiJoystick,
            label: "Simulador",
            path: "/instrucao/simulador",
            resource: "simulador",
            permission: "view",
         },
      ],
   },
   {
      type: "collapse",
      icon: MdPolicy,
      label: "Inteligência",
      scope: "tenant",
      roles: ["inteligencia"],
      children: [
         {
            icon: MdBadge,
            label: "Passaportes",
            path: "/inteligencia/passaportes",
         },
      ],
   },
   {
      type: "collapse",
      icon: FaUsers,
      label: "Pessoal",
      scope: "tenant",
      roles: [
         "ops_avancado",
         "ops_basico",
         "dout_avancado",
         "dout_basico",
         "apoio_avancado",
         "apoio_basico",
      ],
      children: [
         {
            icon: MdAirplaneTicket,
            label: "Missões",
            path: "/cegep/missoes",
            resource: "missoes_cegep",
            permission: "view",
         },
         {
            icon: MdMoney,
            label: "Comissionamento",
            path: "/cegep/comiss",
            resource: "comiss",
            permission: "view",
         },
         {
            icon: MdAccountBalance,
            label: "Dados Bancários",
            path: "/cegep/dados-bancarios",
            resource: "dados_bancarios",
            permission: "view",
         },
         {
            icon: MdAttachMoney,
            label: "Soldos",
            path: "/cegep/soldos",
            resource: "soldo",
            permission: "view",
         },
         {
            icon: MdMoney,
            label: "Diárias",
            path: "/cegep/diarias",
            resource: "diaria",
            permission: "view",
         },
      ],
   },
   {
      // Diretório universal de usuários: visível em ambos os contextos
      // (Sistema e unidade). Ver project-users-universal.
      type: "item",
      icon: MdOutlinePeopleAlt,
      label: "Usuários",
      path: "/users",
      scope: "shared",
      roles: ["apoio_avancado", "apoio_basico", "dout_avancado", "dout_basico"],
   },
   {
      type: "collapse",
      icon: RiAdminLine,
      label: "Admin",
      scope: "system",
      roles: ["admin"],
      children: [
         {
            icon: FaBuilding,
            label: "Organizações",
            path: "/admin/organizacoes",
         },
         {
            icon: FaSitemap,
            label: "Tenants",
            path: "/admin/tenants",
         },
         {
            icon: GiSecurityGate,
            label: "Roles",
            path: "/admin/roles",
         },
         {
            icon: TbLogs,
            label: "Logs",
            path: "/admin/logs",
         },
         {
            icon: MdStorage,
            label: "Storage",
            path: "/admin/storage",
         },
      ],
   },
] as const;
